### ISSUE TITLE
Qual será o escopo inicial da nossa aplicação? Quais funcionalidades ela terá inicialmente?

### ISSUE THREAD

**Issue by josiassoares** [josiassoares/Manager#1]

**Comment by gustavoRaposa** [comment]
Na parte inicial do programa, seria apresentado um menu, onde apresentariam algumas opções como 
1 ) Realizar Vendas ( Pediríamos o código do produto seu valor total e valor de lucro iriam para o estoque )
2 ) Verificar Estoques (Mostrariam alertas de quais produtos estão com estoque baixo, além de ver qual o estoque dos produtos que estão com estoque, após isso ser feito seria interessante tentarmos incrementar um controle para data de validade)
3 ) Fechar Caixa e ver Relatórios (Geraria um relatório do dia em um arquivo TXT )
4 ) Cadastrar produtos ( Cadastra o produto pedindo todas as suas informações )

Vale ressaltar que isso são apenas idéias e não o final definitivo do programa, estando aberto a alterações.
